apiVersion: v1
appVersion: "1.0"
description: Helm chart for the HMCTS Pay bubble frontend service
name: ccpay-bubble-frontend
home: https://github.com/hmcts/ccpay-bubble
version: 0.2.2
maintainers:
  - name: HMCTS Fees & Payments Dev Team
    email: ccpay@hmcts.net
