dependencies:
  - name: payment-api
    version: ~0.0.4
    repository: '@hmctspublic'
  - name: nodejs
    version: 1.3.1
    repository: '@hmctspublic'
  - name: idam-pr
    version: ~2.1.3
    repository: '@hmctspublic'
    tags:
      - idam-pr
