security:
  referrerPolicy: SECURITY_REFERRER_POLICY,
  hpkp:
    maxAge: SECURITY_HPKP_MAX_AGE,
    pins: SECURITY_HPKP_PINS
idam:
  client_id: paybubble
  login_url: IDAM_LOGIN_URL
  api_url: IDAM_API_URL
  web_url: IDAM_AUTHENTICATION_WEB_URL
ccpaybubble:
  url: CCPAY_BUBBLE_URL
  microservice: CCPAY_BUBBLE_MICROSERVICE
s2s:
  url: S2S_URL
payhub:
  url: PAYHUB_API_URL
bulkscan:
  url: CCPAY_BULKSCAN_API_URL
certs:
  key: CERTS_KEY
  crt: CERTS_CRT
session:
  cookieName: JWT_PAYBUBBLE
environment:
  ldPrefix: LD_FLAG_PREFIX
e2e:
  frontendUrl: E2E_FRONTEND_URL
  waitForTimeoutValue: E2E_WAIT_FOR_TIMEOUT_VALUE
  waitForActionValue: E2E_WAIT_FOR_ACTION_VALUE
fee:
  feeRegistrationUrl: FEE_REGISTRATION_URL
  feeJurisdictionUrl: FEE_JURISDICTION_URL
ccd:
  url: CCD_URL
secrets:
  ccpay:
    paybubble-s2s-secret: S2S_KEY
    paybubble-idam-client-secret: IDAM_CLIENT_SECRET
    launch-darkly-client-id: LD_CLIENT_ID
    AppInsightsInstrumentationKey: APPINSIGHTS_INSTRUMENTATIONKEY
    bubble-frontend-redis-connection-string: REDISCLOUD_URL
redis:
  prefix: REDIS_KEY_PREFIX
  ttl: REDIS_TTL  
