security:
  referrerPolicy: SECURITY_REFERRER_POLICY,
  hpkp:
    maxAge: SECURITY_HPKP_MAX_AGE,
    pins: SECURITY_HPKP_PINS
idam:
  client_id: paybubble
  login_url: IDAM_AUTHENTICATION_WEB_URL
  api_url: IDAM_API_URL
ccpaybubble:
  url: CCPAY_BUBBLE_URL
  microservice: CCPAY_BUBBLE_MICROSERVICE
pcipalantenna:
  url: PCIPAL_ANTENNA_URL
  microservice: CCPAY_BUBBLE_MICROSERVICE
pci-pal:
  telephony-selection: TELEPHONY_FEATURE
s2s:
  url: http://rpe-service-auth-provider-demo.service.core-compute-demo.internal
payhub:
  url: http://payment-api-demo.service.core-compute-demo.internal
bulkscan:
  url: http://ccpay-bulkscanning-api-demo.service.core-compute-demo.internal
refunds:
  url: CCPAY_REFUNDS_API_URL
notification:
  url: CCPAY_NOTIFICATION_API_URL
waystopay:
  url: WAYS_TO_PAY_RETURN_URL
postcodelookup:
  url: POSTCODE_LOOKUP_URL
certs:
  key: CERTS_KEY
  crt: CERTS_CRT
session:
  cookieName: JWT_PAYBUBBLE
environment:
  ldPrefix: LD_FLAG_PREFIX
  currentEnv: CURRENT_ENVIRONMENT
e2e:
  frontendUrl: TEST_URL
  testForCrossbrowser: E2E_TEST_FOR_CROSS_BROWSER
fee:
  feeRegistrationUrl: FEE_REGISTRATION_URL
  feeJurisdictionUrl: FEE_JURISDICTION_URL
ccd:
  url: CCD_URL
secrets:
  ccpay:
    paybubble-s2s-secret: RNR42H2GZQAOQUVI
    paybubble-idam-client-secret: ZMRYYAXISRSZPVHN
    launch-darkly-client-id: 5f227f4df775300ba82996dc
    postcode-address-lookup-id: PKQqwTTaCzBYQRJMD1pAQUEaGYGcIEdT
    AppInsightsInstrumentationKey: AppInsightsInstrumentationKey
