security:
  referrerPolicy: origin
idam:
  client_id: paybubble
  login_url: http://localhost:23443/login #https://idam-web-public.aat.platform.hmcts.net
  api_url: http://localhost:23443 #https://idam-api.aat.platform.hmcts.net
session:
  cookieName: SESSION_ID
environment:
  ldPrefix: FEprod
ccpaybubble:
  url: https://localhost
  defaultPort: 3000
  microservice: ccpay_bubble
s2s:
  url: http://localhost:23443 #http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
payhub:
  url: http://localhost:8080 #http://payment-api-prod.service.core-compute-prod.internal
bulkscan:
  url: http://localhost:8081 #http://ccpay-bulkscanning-api-prod.service.core-compute-prod.internal
appInsights:
  roleName: paybubble
e2e:
  frontendUrl: https://localhost:4200/
  waitForTimeoutValue: 2600
  waitForActionValue: 2000
certs:
  key: ./localhost-ssl/localhost.key
  crt: ./localhost-ssl/localhost.crt
fee:
  feeRegistrationUrl: http://localhost:23443/fees #http://fees-register-api-aat.service.core-compute-aat.internal/fees-register/fees
  feeJurisdictionUrl: http://localhost:23443/jurisdictions #http://fees-register-api-aat.service.core-compute-aat.internal/jurisdictions
ccd:
  url: http://localhost:23443
secrets:
  ccpay:
    paybubble-s2s-secret: G5XTFNBUW4P6ZP4F
    paybubble-idam-client-secret: NVYEC2X7XFSRENTU
    launch-darkly-client-id: 5f227f4df775300ba82996dc
    AppInsightsInstrumentationKey: some-key
