security:
  referrerPolicy: origin
idam:
  client_id: paybubble
  login_url: http://localhost:23443/login
  api_url: http://localhost:23443
session:
  cookieName: SESSION_ID
environment:
  ldPrefix: FEprod
ccpaybubble:
  url: https://localhost
  defaultPort: 3000
  microservice: ccpay_bubble
pcipalantenna:
  url: https://paybubble.platform.hmcts.net/ccd-search
  microservice: ccpay_bubble
s2s:
  url: http://localhost:23443
payhub:
  url: http://localhost:8089
bulkscan:
  url: http://localhost:7070
refunds:
  url: http://localhost:8084
notification:
  url: http://ccpay-notifications-service-demo.service.core-compute-demo.internal
postcodelookup:
  url: https://api.os.uk/search/places/v1
appInsights:
  roleName: paybubble
e2e:
  frontendUrl: https://localhost:4200/
  waitForTimeoutValue: 2600
  waitForActionValue: 2000
certs:
  key: ./localhost-ssl/localhost.key
  crt: ./localhost-ssl/localhost.crt
fee:
  feeRegistrationUrl: http://localhost:23443/fees
  feeJurisdictionUrl: http://localhost:23443/jurisdictions
ccd:
  url: http://localhost:23443
secrets:
  ccpay:
    paybubble-s2s-secret: PAYBUBBLE-S2S-SECRET-KEY
    paybubble-idam-client-secret: PAYBUBBLE-IDAM-CLIENT-SECRET-KEY
    launch-darkly-client-id: PAYBUBBLE-LD-CLIENT-ID
    postcode-address-lookup-id: POSTCODE_ADDRESS_LOOKUP_ID
    AppInsightsInstrumentationKey: some-key
