security:
  referrerPolicy: origin
idam:
  client_id: paybubble
  login_url: http://localhost:23443
  api_url: http://localhost:23443
session:
  cookieName: SESSION_ID
environment:
  ldPrefix: FEprod
ccpaybubble:
  url: https://localhost
  defaultPort: 3000
  microservice: ccpay_bubble
pcipalantenna:
  url: https://paybubble.platform.hmcts.net/ccd-search
  microservice: ccpay_bubble
s2s:
  url: http://localhost:8085
payhub:
  url: http://localhost:8091
bulkscan:
  url: http://ccpay-bulkscanning-api-prod.service.core-compute-prod.internal
refunds:
  url: http://ccpay-refunds-api-prod.service.core-compute-prod.internal
notification:
  url: http://ccpay-notifications-service-demo.service.core-compute-demo.internal
waystopay:
  url: https://paymentoutcome-web.demo.platform.hmcts.net/payment
postcodelookup:
  url: https://api.os.uk/search/places/v1
  key: 'NEED APP KEY'
appInsights:
  roleName: paybubble
e2e:
  frontendUrl: https://localhost:4200/
  waitForTimeoutValue: 2600
  waitForActionValue: 2000
certs:
  key: ./localhost-ssl/localhost.key
  crt: ./localhost-ssl/localhost.crt
fee:
  feeRegistrationUrl: http://localhost:23443/fees-register/fees
  feeJurisdictionUrl: http://localhost:23443/jurisdictions
ccd:
  url: http://localhost:23443
secrets:
  ccpay:
    paybubble-s2s-secret: PAYBUBBLE-S2S-SECRET-KEY
    paybubble-idam-client-secret: PAYBUBBLE-IDAM-CLIENT-SECRET-KEY
    launch-darkly-client-id: PAYBUBBLE-LD-CLIENT-ID
    AppInsightsInstrumentationKey: some-key
