security:
  referrerPolicy: origin
idam:
  client_id: ccpay_bubble
  client_secret: IDAM_CLIENT_SECRET
  login_url: http://localhost:23443/login
  api_url: http://localhost:23443
session:
  cookieName: BAR
ccpaybubble:
  url: http://localhost.com
  defaultPort: 3000
  microservice: ccpay_bubble
s2s:
  key: G5XTFNBUW4P6ZP4F
  url: https://rpe-service-auth-provider-aat.service.core-compute-aat.internal
payhub:
  url: https://payment-api-aat.service.core-compute-aat.internal/
appInsights:
  instrumentationKey: some-key
e2e:
  frontendUrl: http://localhost:4200/
  waitForTimeoutValue: 2600
  waitForActionValue: 2000
