security:
  referrerPolicy: origin
idam:
  client_id: paybubble
  client_secret: SFQBNO52G4ITHHDJ
  login_url: https://localhost:8000/login
  api_url: http://localhost:8001
session:
  cookieName: SESSION_ID
ccpaybubble:
  url: https://localhost
  defaultPort: 3000
  microservice: ccpay_bubble
s2s:
  key: G5XTFNBUW4P6ZP4F
  url: https://rpe-service-auth-provider-aat.service.core-compute-aat.internal
payhub:
  url: https://payment-api-aat.service.core-compute-aat.internal/
appInsights:
  instrumentationKey: some-key
e2e:
  frontendUrl: https://localhost:4200/
  waitForTimeoutValue: 2600
  waitForActionValue: 2000
certs:
  key: ./localhost-ssl/localhost.key
  crt: ./localhost-ssl/localhost.crt

